# Generated by Django 4.2.23 on 2025-06-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("itens", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="foto",
            field=models.ImageField(
                blank=True,
                help_text="Foto do item (opcional, mas recomendada)",
                null=True,
                upload_to="itens/fotos/",
            ),
        ),
    ]
