# Generated by Django 4.2.23 on 2025-06-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("itens", "0002_item_foto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="bloco",
            field=models.CharField(
                choices=[
                    ("bloco_1", "Bloco 1"),
                    ("bloco_2", "Bloco 2"),
                    ("bloco_3", "Bloco 3"),
                    ("bloco_a", "Bloco A"),
                    ("bloco_b", "Bloco B"),
                    ("bloco_c", "Bloco C"),
                    ("bloco_d", "Bloco D"),
                    ("bloco_e", "Bloco E"),
                    ("bloco_f", "Bloco F"),
                    ("bloco_g", "Bloco G"),
                    ("bloco_h", "Bloco H"),
                    ("bloco_i", "Bloco I"),
                    ("bloco_j", "Bloco J"),
                    ("calendoscopio", "Calendoscópio/Jornalismo"),
                    ("biblioteca", "Biblioteca Central"),
                    ("restaurante_ru", "RU - Restaurante Universitário"),
                    ("restaurante_fa", "Restaurante Fazendinha"),
                    ("secretaria", "Secretaria Acadêmica"),
                    ("coordenacao_ccomp", "Coordenação de Curso Ciência da Computação"),
                    ("ca_ccomp", "CA - Centro Acadêmico de Ciência da Computação"),
                    ("dojo", "Dojô - Sala de Estudos"),
                    ("diretoria", "Diretoria do Campus de Palmas"),
                    ("reitoria", "Reitoria"),
                    ("lanchonete", "Lanchonete"),
                    ("cuica", "Cuica - CUICA"),
                    ("labtec", "LabTec"),
                    ("prainha", "Praianha"),
                    ("pista_campo", "Pista de Corrida/Campo de Futebol"),
                    ("ponto_onibus", "Ponto de Ônibus Principal"),
                    ("ponto_onibus_reitoria", "Ponto de Ônibus Reitoria"),
                    ("ponto_onibus_j", "Ponto de Ônibus Bloco J"),
                    ("ponto_onibus_jornalismo", "Ponto de Ônibus Jornalismo"),
                    ("outro", "Outro Local"),
                ],
                help_text="Local onde o item foi perdido ou encontrado",
                max_length=30,
            ),
        ),
    ]
