# Generated by Django 5.2.3 on 2025-06-24 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("itens", "0004_auto_remove_reivindicacao"),
        ("itens", "0004_remove_reivindicacaoitem"),
    ]

    operations = []
