# Generated by Django 5.2.3 on 2025-06-24 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("itens", "0006_remove_pontosencontro"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Anuncio",
        ),
    ]
